In [1]:
import numpy as np
from numpy import array,zeros
from numpy.linalg import inv


def find_first_nonzero(column):
    for i in range(len(column)):
        if column[i] != 0:
            return i
    return -1

def swap_2_line(column1,column2):
    temps = column1
    column1 = column2
    column2 = temps
    return column1,column2



def pivot_de_Gauss(A):
    try:
        nrows = len(A)
        for i in range(nrows-1):
            index_nonzero = i+find_first_nonzero(np.array(A,float)[i:,i])
            if index_nonzero > i:
                swap_2_line(A[i],A[index_nonzero])
            for j in range(i+1,nrows):
                if A[i][i] != 0:
                    A[j] = A[j] - (A[j][i]/A[i][i])*A[i]
                else:
                    continue
        return A
    except Exception as e:
        print(e)

def refine(A):
    nrows = len(A)
    for i in range(nrows-1,-1,-1):
        for j in range(i-1,-1,-1):
            
            index_nonzero = i+find_first_nonzero(A[i,i:])
            if index_nonzero >= i:
                A[j] = A[j] - (A[j][index_nonzero]/A[i][index_nonzero])*A[i] 
            else:
                continue
    for i in range(nrows):
        if A[i,i] != 0:
            A[i] = 1/A[i][i]*A[i]+0
        else:
            continue
    return A
def init_matrix():
    arr = []
    m,n = map(int,input('Nhap kich co ma tran he so A:').strip().split()) 
    found_A = False
    while not found_A: 
        arr = []  
        for i in range(m):
            arr.append(input('Nhap hang {}: '.format(i+1)).strip().split())
        if len(arr) == m and all(len(arr[i]) == n for i in range(m)):
            found_A = True
        else:
            print('Khong phu hop kich co')
    found_v = False
    while not found_v:
        v = input('Nhap vector phu hop').split()
        if len(v) == m:
            for i in range(m):
                arr[i].append(v[i])
            found_v = True
        else:
            print('Khong phu hop kich co')
    
    return np.array(arr,float)





In [2]:
A = np.array([[1,1,1,1,1],[1,-1,-1,-1,2],[-1,-1,1,1,3],[-3,1,-3,-7,2]],float)
print('Ma tran lien hop sau khi cheo hoa co dang \n', refine(pivot_de_Gauss(A)))

Ma tran lien hop sau khi cheo hoa co dang 
 [[ 1.    0.    0.    0.    1.5 ]
 [ 0.    1.    0.    0.   -2.5 ]
 [ 0.    0.    1.    0.    5.75]
 [ 0.    0.    0.    1.   -3.75]]


In [4]:
mat1 = np.array([[1,-1,-1,0],[1,0,-1,0],[1,-1,0,0],[0,0,0,1]],float)
mat2 = np.array([[2,-1,-1,-1],[1,0,-1,-1],[1,-1,0,-1],[1,-1,-1,0]],float)
print(inv(mat1))
print(inv(mat2))

[[-1.  1.  1.  0.]
 [-1.  1.  0.  0.]
 [-1.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 2. -1. -1. -1.]
 [ 1.  0. -1. -1.]
 [ 1. -1. -0. -1.]
 [ 1. -1. -1. -0.]]


In [1]:
import numpy as np
def find(A,B):
    while True:
        v = np.random.randint(-5,6,size=4)
        pr_A = A.dot(v)
        pr_B = B.dot(v)
        if all(item in range(-10,11) for item in pr_A) and all(item in range(-10,11) for item in pr_B):
            return v
A =  np.array([[-6,-8,0,8],[2,4,5,3],[3,5,4,0],[1,5,4,-3],[2,0,0,3],[0,-6,-3,9]])
B = np.array([[6,4,7,2],[1,0,4,3],[-2,-4,2,4],[-8,6,-1,1],[0,-4,10,10],[4,0,9,6]])
root = np.array([-1,0,1,0])

print(A, A.dot(root))
print(B, B.dot(root))



[[-6 -8  0  8]
 [ 2  4  5  3]
 [ 3  5  4  0]
 [ 1  5  4 -3]
 [ 2  0  0  3]
 [ 0 -6 -3  9]] [ 6  3  1  3 -2 -3]
[[ 6  4  7  2]
 [ 1  0  4  3]
 [-2 -4  2  4]
 [-8  6 -1  1]
 [ 0 -4 10 10]
 [ 4  0  9  6]] [ 1  3  4  7 10  5]
